name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} | tee -a ~/.ssh/known_hosts

      - name: Debug EC2 Variables
        run: |
          echo "EC2_HOST is: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER is: ${{ secrets.EC2_USER }}"
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then echo "SSH_PRIVATE_KEY is not set"; else echo "SSH_PRIVATE_KEY is set"; fi
          if [ -z "${{ secrets.EC2_HOST }}" ]; then echo "EC2_HOST is not set"; fi
          if [ -z "${{ secrets.EC2_USER }}" ]; then echo "EC2_USER is not set"; fi

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -x  # Enable debugging

          # Kill any process running on port 4000 to avoid conflicts
          sudo lsof -t -i:4000 | xargs kill -9 || echo "No process using port 4000"

          # Navigate to the application directory
          cd ~/projects/random/Backend_Part_Nestjs

          # Pull the latest changes from the main branch
          git pull origin main

          # Install dependencies (npm)
          npm install

          # Install PM2 if not installed
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          # Set the Firebase API key from GitHub Secrets
          export FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}"

          # Start the NestJS application with PM2 on port 4000
          pm2 start npm --name "nestjs-app" -- run start  
          EOF

      - name: Reload Nginx
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo systemctl reload nginx
          EOF
