name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t khalidelmodir/backend:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push khalidelmodir/backend:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.60.80.252 | tee -a ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.60.80.252 << 'EOF'
          set -x  # Enable debugging

          # Stop any existing containers to avoid conflicts
          sudo docker stop backend-app || echo "No running container named backend-app"
          sudo docker rm backend-app || echo "No container named backend-app to remove"

          # Pull the latest Docker image
          sudo docker pull khalidelmodir/backend:latest

          # Run the new container
          sudo docker run -d --name backend-app -p 4000:4000 khalidelmodir/backend:latest

          # Optionally, tail your app logs if you have set up logging
          # sudo docker logs -f backend-app || echo "No log files found"
          EOF
