name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t KhalidElModir/backend:latest .
        docker push KhalidElModir/backend:latest

    - name: SSH into server and deploy
      run: |
        ssh -i "${{ secrets.EC2_SSH_KEY }}" ec2-user@your-ec2-ip-address 'cd /path-to-your-app && docker-compose pull && docker-compose up -d'
